version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: AdharaProjects/admin-cli:a564d6
    environment:
      MAX_HEAP_SIZE: 4096m
      HEAP_NEWSIZE: 1024m
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: test
          command: |
            export MY_VAR="JasonWasHere"
            echo $CIRCLE_BRANCH
            echo $CI_PULL_REQUEST
            echo $ORG
            echo $PROJECT
            echo $CIRCLE_PR_NUMBER
            echo $GH_AUTH_TOKEN
            echo ${CIRCLE_PULL_REQUEST##*/}
            export PR_NUMBER=${CIRCLE_PULL_REQUEST##*/}
            echo "https://api.github.com/repos/JasoonS/testCircleCi/pulls/${CIRCLE_PULL_REQUEST##*/}?access_token=$GH_AUTH_TOKEN"

            if curl "https://api.github.com/repos/JasoonS/testCircleCi/pulls/${CIRCLE_PULL_REQUEST##*/}?access_token=$GH_AUTH_TOKEN" | grep -q 'JasoonS:master'; then
              echo "hello"
            else
              echo "fail"
            fi
            if curl "https://api.github.com/repos/JasoonS/testCircleCi/pulls/${CIRCLE_PULL_REQUEST##*/}?access_token=$GH_AUTH_TOKEN" | grep -q 'JasoonS:develop'; then
              echo "master"
            else
              echo "master-fail"
            fi
            if [[ ! -z "$CIRCLE_PULL_REQUEST" || curl "https://api.github.com/repos/JasoonS/testCircleCi/pulls/${CIRCLE_PULL_REQUEST##*/}?access_token=$GH_AUTH_TOKEN" | grep -q 'JasoonS:master' ]]; then
              echo "master-full"
            else
              echo "master-fail"
            fi
            echo "before - wanted"
            echo $MY_VAR
            echo "before - end"
            url="https://api.github.com/repos/JasoonS/testCircleCi/pulls/$PR_NUMBER?access_token=$GH_AUTH_TOKEN"
            echo $url
            curl "$url"

workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          context: cash_tokenizer_ci
